controller_manager: # Node name
  ros__parameters:
    update_rate: 30 # Has to be an integer otherwise errors are encountered

    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster 


diff_controller:
  ros__parameters:
    
    publish_rate: 50.0 # Has to be a double otherwise errors are encountered

    base_frame_id: base_footprint

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.48
    wheel_radius: 0.072

    # Obtained from https://wiki.ros.org/diff_drive_controller
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0] 

    # Whether the input has a time stamp or not
    use_stamped_vel: false

    # Odometry fused with IMU is published by robot_localization, so no need to publish a TF
    # based on encoders alone (https://wiki.ros.org/diff_drive_controller)
    enable_odom_tf: false

imu_broadcaster:
  ros__parameters:
    publish_rate: 100.0
    sensor_name: mpu6050
    frame_id: imu_link
   
   # 500 data points used to calculated covariances
    static_covariance_orientation: [1.87745e-05, 0.0, 0.0, 8.29082e-06, 0.0, 0.0, 1.00332e-08, 0.0, 0.0]
    static_covariance_angular_velocity: [1.61869e-05, 0.0, 0.0, 3.00882e-06, 0.0, 0.0, 2.8125e-06, 0.0, 0.0]
    static_covariance_linear_acceleration: [0.000666834, 0.0, 0.0, 0.00362427, 0.0, 0.0, 0.00250045, 0.0, 0.0]
    


